### ISSUE TITLE
Doesn't escape strings with newlines.

### ISSUE THREAD

**Issue by wsaglime** [yaslab/CSV.swift#102]
I would love to submit a fix, @yaslab please let me know if I can go ahead. 

Also-- I see you have some automated tests. I've never run automated tests in Xcode, but I was thinking I can figure it out and add a contributing.md file for this repo to document how to run and add tests for future features or bugfixes. Might make it easier for others to open up good pull requests and share the workload.

**Comment by mildm8nnered** [comment]
I'd be very interested in this feature

**Comment by yaslab** [comment]
Sorry for the late reply. Bug fixes are welcome!

Unit testing the code in this repository is easy. You can run it by pressing `cmd + U` in Xcode. Or, run the `swift test` command in the repository root directory.

**Comment by wsaglime** [comment]
Thanks for the unit test instructions! No need for a fix anymore, https://github.com/yaslab/CSV.swift/pull/103 took care of it. Thanks @vipt 👍
