### ISSUE TITLE
Output CSV?

### ISSUE THREAD

**Issue by kgn** [yaslab/CSV.swift#22]
Are there plans to add outputting csv files as well?

**Comment by yaslab** [comment]
I don't plan to add outputting feature for now.

**Comment by kgn** [comment]
To bad. This library is great, would be even better with output!

**Comment by yaslab** [comment]
I added the `CSVWriter` class in version 2.0.0. Please see [README.md](https://github.com/yaslab/CSV.swift#usage-for-writing-csv) for usage.
