### ISSUE TITLE
Strange output?

### ISSUE THREAD

**Issue by kgn** [yaslab/CSV.swift#23]
For the most part this library works great! But I'm encountering some strange things when iterating over a parsed CSV in my unit tests. Sometimes the parsing seems to fail and the values are populated with goggly goop like this column value of `\0\0\0èä\u{05}\0\0\0\0\0\0\0\0\0\0\0\0\0+\u{07}\u{01}\0\0\0Ø`.

Not sure if anyone else has encounter this, I haven't been able to figure out any sort of patter as to why it is happening.

**Comment by Boidkan** [comment]
Getting the same thing.

**Comment by kgn** [comment]
@yaslab any ideas what could be causing this?

**Comment by yaslab** [comment]
@kgn I don't know the cause yet.

Although it may not be related to this issue, I think that it may not be good to have some functions implemented in a `struct`. I'm currently working on replacing `struct` with `class`.

I will release this weekend so please try it.

**Comment by yaslab** [comment]
@kgn I released version 2.0.0 in June. As it may have been fixed, please try out the new version.

**Comment by Patrick3131** [comment]
Has this been fixed? I tried to use the Framework but I also get a wrong output like this:
Optional(["O\0r\0d\0e\0r\0U\0u\0i\0d\0", "\0E\0x\0c\0h\0a\0n\0g\0e\0", "\0T\0y\0p\0e\0", "\0Q\0u\0a\0n\0t\0i\0t\0y\0", "\0L\0i\0m\0i\0t\0", "\0C\0o\0m\0m\0i\0s\0s\0i\0o\0n\0P\0a\0i\0d\0", "\0P\0r\0i\0c\0e\0", "\0O\0p\0e\0n\0e\0d\0", "\0C\0l\0o\0s\0e\0d\0/\0a\03\04\06\04\06\06\05\0-\03\07\07\00\0-\04\02\03\06\0-\0b\07\03\08\0-\09\08\0e\00\02\08\0c\0b\00\08\07\06\0", "\0B\0T\0C\0-\0E\0T\0H\0", "\0L\0I\0M\0I\0T\0_\0S\0E\0L\0L\0", "\01\0.\05\00\00\00\00\00\00\00\0", "\00\0.\00\03\05\07\09\09\09\07\0", "\00\0.\00\00\00\01\03\04\02\02\0", "\00\0.\00\05\03\06\09\09\09\03\0", "\01\02\0/\01\06\0/\02\00\01\07\0 \09\0:\04\04\0:\04\02\0 \0P\0M\0", "\01\02\0/\01\06\0/\02\00\01\07\0 \09\0:\04\07\0:\03\05\0 \0P\0M\0"])

My code looks like this:
    static func csvImport(){
        
        let stream = "OrderUuid,Exchange,Type,Quantity,Limit,CommissionPaid,Price,Opened,Closed/a3464665-3770-4236-b738-98e028cb0876,BTC-ETH,LIMIT_SELL,1.50000000,0.03579997,0.00013422,0.05369993,12/16/2017 9:44:42 PM,12/16/2017 9:47:35 PM"
        let csv = try! CSVReader(string: stream, hasHeaderRow: true)
        let headerRow = csv.headerRow
        print("\(headerRow)")
    }
