### ISSUE TITLE
Skip Comma in Date

### ISSUE THREAD

**Issue by martheli** [yaslab/CSV.swift#31]
Is there anyway to avoid the comma in a date, for example jan 8, 2007 so that it puts the whole date in one cell instead of two cells? Something to ignore the comma?

**Comment by yaslab** [comment]
@martheli Which do you use `CSVReader` or `CSVWriter`?

In the CSV format, enclose a string containing commas in quotes(`"`) to treat string as one field.

### When using `CSVWriter`

You can pass `true` for the `quoted` parameter of the `write` method.
For example:

```
csv.beginNewRow()
try! csv.write(field: "jan 8, 2007", quoted: true)
```

### When using `CSVReader`

Unfortunately, we can't read a string containing commas that are not enclosed in `"` as a single field.
The string containing commas must be output with `"` in the CSV file.
