### ISSUE TITLE
How read cvs file with encoding: Windows 1251

### ISSUE THREAD

**Issue by dimonuch1** [yaslab/CSV.swift#32]

**Comment by yaslab** [comment]
@dimonuch1 

If the CSV file size is small, you can read the file into a `String` and pass it to the initializer. For example,

```swift
let path = "/path/to/file.csv"
let str = try! String(contentsOfFile: path, encoding: .windowsCP1251)
let csv = try! CSVReader(string: str)
// Some code for reading CSV.
// ...
```

---

If the CSV file size is too large to fit in memory, you can use a wrapping class of `InputStream` like [this code](https://github.com/yaslab/InputStreamReader/blob/c7eddcc5bd6b4889c370fa1228cba19636f27e6f/Sources/InputStreamReader.swift). Usage is as follows. Please note that this code requires a link to `libiconv`.

```swift
let url = URL(fileURLWithPath: "/path/to/file.csv")
let stream = InputStream(url: url)!
// `InputStreamReader` is a wrapper class for `InputStream`.
let cp1251 = InputStreamReader.Encoding(codePage: 1251)!
let reader = InputStreamReader(stream: stream, from: cp1251, to: .utf32BE)!
let csv = try! CSVReader(stream: reader, codecType: UTF32.self, endian: .big)
// Some code for reading CSV.
// ...
```
