### ISSUE TITLE
GCD Support for Large Files?

### ISSUE THREAD

**Issue by bchynds** [yaslab/CSV.swift#40]
Any way to speed this up with GCD?  I have a CSV with 50k+ rows that I need to crunch through and just incrementing a counter takes about 45 seconds on my iPad.

```swift
// Time began:
let startTime = Date()

// Read the CSV file:
let filePath = Bundle.main.path(forResource: "foo", ofType: "csv")
let stream = InputStream(fileAtPath: filePath!)
let csv = try! CSVReader(stream: stream!, hasHeaderRow: true)

// Count the rows:
var counter = 0
while csv.next() != nil {
    counter += 1
}

// Check the results:
print("Rows: \(counter)")
print("Elapsed time: \(startTime.timeIntervalSinceNow) seconds")
```

```
Output:
Rows: 52229
Elapsed time: -46.1442109942436 seconds
```

**Comment by percypyan** [comment]
I think the solution isn't GDC but a dedicated function to count rows without parsing and splitting them into `[String]`.

**Comment by yaslab** [comment]
I close this issue because it is outdated. By the way, speed has been improved with pull request #65.
