### ISSUE TITLE
Swift 4/Xcode 9 support?

### ISSUE THREAD

**Issue by haemi** [yaslab/CSV.swift#41]
is support for Swift 4/XCode 9 planned?

**Comment by yaslab** [comment]
@haemi [Version 2.1.0](https://github.com/yaslab/CSV.swift/releases/tag/2.1.0) supports Swift 4 / Xcode 9, so please try it!

**Comment by haemi** [comment]
I am using the latest version, but I always get this error when compiling:

![image](https://user-images.githubusercontent.com/183958/31213156-4ac0a60c-a9a5-11e7-8f3d-5a927482317f.png)

**Comment by philmctim** [comment]
I'm a bit of a Swift newbie, but I'm pretty sure I upgraded my project to Swift 4, got tons of errors with the CSV library, upgraded the library to v2.1.0 and all the errors went away!

Thanks!

**Comment by mbarclay** [comment]
#53 addresses Xcode 9.3 and Swift 4.0 compatibility. Now merged into the master branch – thanks @yaslab
