### ISSUE TITLE
can the file path be written in URL instead of string ?

### ISSUE THREAD

**Issue by MatinC** [yaslab/CSV.swift#42]
let itemList = objects.dataName
        let fileManager = FileManager.default
        do {
            let documentDirectory = try fileManager.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
            let stream = OutputStream(toFileAtPath: documentDirectory.appendingPathComponent(<#T##pathComponent: String##String#>), append: false)
            let csv = try! CSVWriter(stream: stream!)
            try! csv.write(row: ["name", "x", "y", "width", "height"])
            for _ in 0..<(itemList.count-1) {
                try! csv.write(row: [String(describing: objects.dataName.last), String(describing: objects.dataX.last), String(describing: objects.dataY.last), String(describing: objects.boundingX.last), String(describing: objects.boundingY.last)])
            }
                    csv.stream.close()
        } catch {
            print("oops something went wrong")
        }

something right this? because I want to create a new file's name for every .csv save files

**Comment by yaslab** [comment]
> let documentDirectory = try fileManager.url(for: .documentDirectory, ...
> let stream = OutputStream(toFileAtPath: documentDirectory.appending ...

In this case, you can use `OutputStream (url:append:)` instead of `OutputStream(toFileAtPath:append:)`. e.g.

```
let documentDirectory = fileManager.urls(for: .documentDirectory, in: .userDomainMask)[0]
let csvFile = documentDirectory.appendingPathComponent("output.csv")
let stream = OutputStream(url: csvFile, append: false)
```
