### ISSUE TITLE
Getting error in let csv = try! CSVWriter(stream: stream)

### ISSUE THREAD

**Issue by bidhan01071992** [yaslab/CSV.swift#51]
I am trying to update a CSV file in local intranet server.

guard let stream = OutputStream(toFileAtPath: peopleListSheetURL, append: false) else { return }
        stream.open()
        ** peopleListSheetURL is a path to a CSV file in local intranet server**
        let csv = try! CSVWriter(stream: stream).  ---**Here getting error Fatal error: 'try!' expression unexpectedly raised an error: CSV.CSVError.cannotOpenFile: file /BuildRoot/Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-900.0.74.1/src/swift/stdlib/public/core/ErrorType.swift, line 181 **
        
        for skillDetail in skillDB {
            if Int(skillDetail.value) == 0 {
                continue
            } else {
                try! csv.write(row: [empSelectionLabel.text!, skillDetail.key, skillDetail.value])
                csv.stream.close()
            }
        }

**Comment by yaslab** [comment]
Please check `stream.streamStatus` after one line of `stream.open()`.
If `stream.streamStatus != .open`, it has failed to open the file in write mode.
Perhaps, the user executing the process may not have write permissions.
