### ISSUE TITLE
pod 'CSV.swift', '~> 2.2.1'

### ISSUE THREAD

**Issue by dadidu67** [yaslab/CSV.swift#59]
causes

[!] CocoaPods could not find compatible versions for pod "CSV.swift":
  In Podfile:
    CSV.swift (~> 2.2.1)

None of your spec sources contain a spec satisfying the dependency: `CSV.swift (~> 2.2.1)`.

**Comment by yaslab** [comment]
@dadidu67 Could you try `pod repo update` before `pod install`?

**Comment by dadidu67** [comment]
Well I could do but the real question is, was causes or what might causes the error? After the error I did try SwiftCSVExport with no problems.
