### ISSUE TITLE
linux not build

### ISSUE THREAD

**Issue by a72** [yaslab/CSV.swift#67]
How to avoid mistakes?
/swift/lib/CSV.swift/Sources/CSV/CSVReader+Decodable.swift:345:31: error: use of unresolved identifier 'kCFBooleanTrue'
                if number === kCFBooleanTrue as NSNumber {
                              ^~~~~~~~~~~~~~
/swift/lib/CSV.swift/Sources/CSV/CSVReader+Decodable.swift:347:38: error: use of unresolved identifier 'kCFBooleanFalse'
                } else if number === kCFBooleanFalse as NSNumber {

**Comment by yaslab** [comment]
Thank you for reporting! I will fix it this weekend.
