### ISSUE TITLE
Support for Int-type CodingKey

### ISSUE THREAD

**Issue by sstadelman** [yaslab/CSV.swift#71]
I've been working to add support & tests for `Int` typed `CodingKey`, for supporting `Decodable` with or without headers.  Can I claim this feature if you're not already on it?

Expected Behavior:

 - When implementing `Decodable` for a type, developer can use `Int` type enum for `CodingKey`
 - Value of the enum maps to column of the data
 - Header row should be ignored
 - Developer continues to use `Configuration` struct to indicate the presence/absence of header row

Example:

```swift
    class IntKeyedDecodableExample: SupportedDecodableExample {
        private enum CodingKeys: Int, CodingKey {
            case intKey = 2
            case stringKey = 0
            case optionalStringKey = 1
            case dateKey = 4
            case enumKey = 5
        }
    }
```

**Comment by sstadelman** [comment]
Submitted #72

**Comment by yaslab** [comment]
Pull request merged. Thank you!
