### ISSUE TITLE
Issue with text containing double quotes

### ISSUE THREAD

**Issue by chungfk** [yaslab/CSV.swift#85]
Hi,

I've got a issue with string containing double quotes (").

Ex: The string in CSV file looks like this:
"Click "Yes" to continue on"

When using this library to read it, the output comes out like so:
"Click \"es\"to continue on"

The character Y is missing, and there is no space between the later half of the double qoute and the next word.

How to fix this?

**Comment by yaslab** [comment]
Please use the string `"Click ""Yes"" to continue on"` instead. The specification (RFC4180) referenced by this library have the following descriptions.

>   7.  If double-quotes are used to enclose fields, then a double-quote
>       appearing inside a field must be escaped by preceding it with
>       another double quote.  For example:
>
>       "aaa","b""bb","ccc"
