### ISSUE TITLE
CSV Deprecated compiler warning

### ISSUE THREAD

**Issue by robwithhair** [yaslab/CSV.swift#94]
![image](https://user-images.githubusercontent.com/6692245/61141114-bc3a6680-a4c4-11e9-8823-745713c5529a.png)

This is encountered when using swift package manager and Xcode 10.2.1

**Comment by yaslab** [comment]
Thank you for reporting! I will fix this soon.

**Comment by yaslab** [comment]
This issue has been fixed in pull request #93.
